package com.wabackuppro.data.local.entities

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * BackupRecord represents a single backup execution in the local Room database.
 */
@Entity(tableName = "backup_records")
data class BackupRecord(
    // Unique identifier for the backup record, auto-generated by Room
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    // The timestamp when the backup was initiated, typically stored as a Unix epoch in milliseconds
    val timestamp: Long,

    // The name of the folder created in Google Drive for this specific backup (e.g., "WABackup_2026-07-18")
    val folderName: String,

    // The total number of files that were discovered and queued for backup
    val totalFiles: Int,

    // The number of files successfully uploaded to Google Drive
    val successCount: Int,

    // The number of files that failed to upload after all retry attempts
    val failCount: Int,

    // A web link to the created Google Drive folder, allowing the user to view it directly
    val driveFolderLink: String?,

    // The total duration the backup job took to complete, in seconds
    val durationSeconds: Long,

    // 📋 Reference to the uploaded files manifest (JSON summary or array of file path + SHA-256 hash + Drive fileId).
    // Storing content hashes (SHA-256) rather than relying on filename/size alone is necessary because:
    // 1. Files with identical names and byte sizes can have changed content (e.g., database overwrites or appended media).
    // 2. WhatsApp media files can be replaced or re-saved without changing file size or display name.
    // 3. Hashes provide a cryptographic guarantee of exact file matching across incremental backups.
    val uploadedFilesManifest: String? = null
)
