package com.wabackuppro.data.local.entities

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * BackupRecord represents a single backup execution in the local Room database.
 */
@Entity(tableName = "backup_records")
data class BackupRecord(
    // Unique identifier for the backup record, auto-generated by Room
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    // The timestamp when the backup was initiated, typically stored as a Unix epoch in milliseconds
    val timestamp: Long,

    // The name of the folder created in Google Drive for this specific backup (e.g., "WABackup_2026-07-18")
    val folderName: String,

    // The total number of files that were discovered and queued for backup
    val totalFiles: Int,

    // The number of files successfully uploaded to Google Drive
    val successCount: Int,

    // The number of files that failed to upload after all retry attempts
    val failCount: Int,

    // A web link to the created Google Drive folder, allowing the user to view it directly
    val driveFolderLink: String?,

    // The total duration the backup job took to complete, in seconds
    val durationSeconds: Long
)
